# Generated by Django 3.1.4 on 2021-08-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('stanje', models.IntegerField()),
            ],
            options={
                'db_table': 'proizvodi',
                'managed': False,
            },
        ),
    ]
