# Generated by Django 3.1.4 on 2021-08-30 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tauretisStatistics', '0002_faktura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faktura',
            options={},
        ),
    ]
