# Generated by Django 3.1.4 on 2021-08-30 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tauretisStatistics', '0003_auto_20210830_0310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proizvod',
            options={},
        ),
        migrations.AlterModelTable(
            name='faktura',
            table=None,
        ),
    ]
