# Generated by Django 3.1.4 on 2021-08-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tauretisStatistics', '0004_auto_20210830_0318'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proizvod',
            table=None,
        ),
    ]
