# Generated by Django 3.1.4 on 2021-08-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tauretisStatistics', '0005_auto_20210830_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='proizvod',
            name='cena',
            field=models.FloatField(default=0),
        ),
    ]
